services:
  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crm_system
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crm_system.sql:/docker-entrypoint-initdb.d/crm_system.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:1234@mysql:3306/crm_system
      - DATABASE_HOST=mysql
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    container_name: nextjs

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - nextjs
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}
